### ISSUE TITLE
Only displays one error at a time.

### ISSUE THREAD

**Issue by dhagerty9009** [AtomLinter/linter-reek#10]
This is related to #9. Due to some issues with the regexes used, the linter only finds the first error produced. Related to this is getting the JSON output option of the `reek` executable to be read by Linter.

**Comment by ahmadseleem** [comment]
Here you go:

a = "[8]:App has no descriptive comment (IrresponsibleModule)"

(parseInt(a.match(/\[([0-9]+)\]/)[1]))

but Linter API requires an Array like:
 [[0,0], [0,1]]
