### ISSUE TITLE
linter-reek passing invalid messages to linter

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-reek#11]
It appears that `linter-reek` is passing messages of an invalid format to the `linter` package, causing issues to be reported against the `linter` package (https://github.com/atom-community/linter/issues/850#issuecomment-134504554).

Steps to reproduce:

0. Open a fresh Atom profile
0. Install `linter` and `linter-reek` packages
0. Create a Ruby file with content (I used the example [here](https://github.com/troessner/reek#example))
0. Trigger a lint

**Comment by steelbrain** [comment]
In any case, we should be catching those invalid messages in linter, can I get to see an example invalid error object please?

**Comment by Arcanemagus** [comment]
![image](https://cloud.githubusercontent.com/assets/427137/9474737/48550b7c-4b17-11e5-93fe-25e238e138a2.png)
```
JSON.stringify(message)
"{"type":"warning","text":["Dirty#awful has unused parameter 'y' (UnusedParameters)\r\n",""],"filePath":"C:\\Users\\Landon\\Desktop\\wtf.rb","range":{"start":{"row":0,"column":0},"end":{"row":0,"column":0}},"key":"{\"type\":\"warning\",\"text\":[\"Dirty#awful has unused parameter 'y' (UnusedParameters)\\r\\n\",\"\"],\"filePath\":\"C:\\\\Users\\\\Landon\\\\Desktop\\\\wtf.rb\",\"range\":{\"start\":{\"row\":0,\"column\":0},\"end\":{\"row\":0,\"column\":0}}}","class":"warning","currentFile":true,"currentLine":false}"
```

Need anything else? It looks like text is an array and shouldn't be.

**Comment by steelbrain** [comment]
Ah right. I think we're gonna need a spec for that in the core linter, as well as a type check.

**Comment by kieranklaassen** [comment]
+1

**Comment by mttrs** [comment]
+1

**Comment by Arcanemagus** [comment]
@dhagerty9009 will you be able to take this on, or do you want somebody else to take a look?

**Comment by dhagerty9009** [comment]
I'm a little swamped at work, so if someone else can fix this issue that would be fantastic.

**Comment by sanrodari** [comment]
+1

**Comment by dhagerty9009** [comment]
I'm closing this issue, as #13 has been merged in.
