### ISSUE TITLE
Implement specs

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-reek#26]
It looks like this linter does not currently have any specs written for it, adding it to the list being maintained [here](https://github.com/AtomLinter/Meta/issues/11) for tracking.

Specs do not need to be super detailed, as they should mainly test whether the package is properly running the linter plugin and parsing its messages. Leave testing of the linter functionality to the author of the linter.

If you need any help feel free to ask!

**Comment by dhagerty9009** [comment]
I'll get on this. I've got a big milestone due for a project at work this week, and once that's done I'll get to work writing out some simple specs.

**Comment by Arcanemagus** [comment]
If you want help I can throw some basic specs together.

**Comment by dhagerty9009** [comment]
@Arcanemagus If you wouldn't mind getting a branch set up with some basic specs, I should be able to work on it tomorrow and get this closed.

**Comment by Arcanemagus** [comment]
Okay

**Comment by dhagerty9009** [comment]
I like it. Honestly, for now I think this might be enough for our specs. It verifies that the linter is loaded and responds properly to dirty and clean files. Anything more I can think of implementing will just be testing Reek itself.

**Comment by Arcanemagus** [comment]
Really the only thing that could be tested further is the executable path and any other settings that can be configured.
