### ISSUE TITLE
ESLint + Babel breaking build

### ISSUE THREAD

**Issue by dhagerty9009** [AtomLinter/linter-reek#51]
There is a fix in the pipeline as outlined in eslint/eslint#5476, it should be landing sometime in the beginning of next week.

**Comment by dhagerty9009** [comment]
Fixed in #52 (I don't know why that claimed the tests were failing, everything came through green.

**Comment by Arcanemagus** [comment]
They were failing before I removed `babel-eslint` :wink:

It's not necessary to use it to parse this project's code, and it's been the cause of both of the last two major "`eslint`" issues so I just removed it in #52.
