### ISSUE TITLE
Change default annotation level to 'warning'

### ISSUE THREAD

**Issue by zl4bv** [AtomLinter/linter-reek#7]
Reek [reports](https://github.com/troessner/reek/blob/develop/README.md#example) code smells as 'warnings'.

Therefore, could the default annotation level of this linter be changed to 'warning'? (Currently set to 'error'...)

**Comment by dhagerty9009** [comment]
I'll get that going. It makes sense, since code smells aren't breaking, but still to be avoided.

**Comment by dhagerty9009** [comment]
This was solved in the migration to the new Linter API. I'm closing the issue.
