### ISSUE TITLE
Update to ES2015

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-reek#88]
@dhagerty9009 Any objections to me re-writing this package in ES2015?

**Comment by dhagerty9009** [comment]
Go ahead and open a PR for it.

**Comment by Arcanemagus** [comment]
Cool, I'll put it up after I get the two that are currently up merged 😉.

**Comment by dhagerty9009** [comment]
I went ahead and made a branch for this issue, aptly named 'update-to-es2015'.
