### ISSUE TITLE
Messages produced while linting files aren't listed on the lines that produced the error.

### ISSUE THREAD

**Issue by dhagerty9009** [AtomLinter/linter-reek#9]
For instance, if there is a code smell on line 20 of `some_file.rb` that is being linted, the message produced by that smell is shown and listed as though it were produced on line 1 of the file.

The issue comes from the `range` argument for the message to be returned [here](https://github.com/AtomLinter/linter-reek/blob/e6fe0d287d434cd7b3a7125ac36c593426429c23/lib/linter-reek.coffee#L47-49)

**Comment by ahmadseleem** [comment]
one Thing is that there's no column in the out put!
Just the line number.
I think that *Linter* API require line and column.
yes, the column could be hard coded to 1 or so...
